before_install:
  - gem update --system

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

test:
  adapter: postgresql
  database: librarium_test

language: ruby
rvm:
  - 2.4.0
